# Site settings
title: 101 Tech
email: webcontact@the101tech.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "the101tech" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: the101tech
github_username: the101tech

# Build settings
markdown: kramdown
